### PR TITLE
fix(collections): importing ABCs from collections directly is deprecated

### PR DESCRIPTION
**Pull request by tvuillemin**
Changes proposed in this pull request:
- Fix the import path of the ABC classes used in the project.

Attention: @prkumar

### CODE REVIEW

**Comment by prkumar** [comment]
Thanks for fixing this tech debt, @tvuillemin! LGTM

**Review by prkumar — CHANGES_REQUESTED** [review]
Thanks for tackling this, @tvuillemin! I have two suggestions before approving this.

First, there are other usages of the `abc` module that need to be fixed. For completion, could you address these as well in your PR? Here is a GitHub query for all usages that I could find: https://github.com/prkumar/uplink/search?q=collections.Mapping+OR+collections.Iterable+OR+collections.Sequence&unscoped_q=collections.Mapping+OR+collections.Iterable+OR+collections.Sequence

Second: in general, this library follows Google's Python style guide. Accordingly, when importing submodules, the recommendation is to use `from abc import collections` rather than `import collections.abc` [source](https://google.github.io/styleguide/pyguide.html#224-decision). Could you update the PR to follow this convention?

**Comment by tvuillemin** [comment]
Hi!

Done. I tried to respect the conventions you are using. I had a doubt though, regarding `collections.namedtuple` for instance. Would you rather have two import lines, to keep the `collections` prefix for `namedtuple`, or a single line `from collections import abc, namedtuple` and drop the prefix? I did the former in this commit, just let me know if you would have preferred the latter.

I would just like to add a small remark, if you don't mind. It felt a bit weird to write `from collections import abc`, for the `abc` prefix generally refers to the [abc](https://docs.python.org/3/library/abc.html) package of the standard library for abstract classes. Wouldn't it be slightly less confusing to use `from collections.abc import Mapping` and drop the prefix entirely? Just a suggestion of course; your repo, your style.

Cheers.

**Comment by prkumar** [comment]
@tvuillemin - Thanks for addressing the other usages and updating the imports to adhere to the style guide!

Regarding the import statement for `namedtuple`: I think keeping a separate import line adheres best to the style guide, so no need to change in this regard.

Regarding your second point, to avoid clashing with the `abc` module, I think another option to do an `import as`: e.g., `from collections import abc as collections_abc`. I'm fine with keeping the imports as is and addressing any future conflicts as they arise, but feel free to update to use either the alternative I described here or the `from collections.abc import Mapping` alternative you mentioned in your comment. I'm not too beholden to the style guide, so either works for me!

**Review by prkumar — APPROVED** [review]
Added thoughts in https://github.com/prkumar/uplink/pull/201#issuecomment-699527926

**Pull request merged**
